### ISSUE TITLE
exif2timestream not working on phenocam server

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#158]
Not sure what broke it but this needs to never stop working. it gets called by an automated task to process all incoming images from all the timelapse camera. First priority when making any changes to anything on the phenocam server should be to keep this working since it is essential to all downstream workflow. I'm not sure if it got uninstalled earlier or if some change to it broke it, you might need to discuss with kevin to get it working.
Calling code that's run by the task scheduler and other related infor is on the E drive on phenocam here:
E:\a_processes\py_MakeTimeStream

**Comment by Joelgranados** [comment]
Is this still an issue? Where is this code? is this even part of timestreamlib?

**Comment by Joelgranados** [comment]
Please reopen if it is still an issue
