### ISSUE TITLE
numeric values in ~fullres-audit.csv file should be defined

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#159]
need a list of what they mean written down somewhere.

**Comment by Joelgranados** [comment]
We can add a header part to the audit.csv that container the error code and their meanings. This can be taken out of the exception classes.

**Comment by Joelgranados** [comment]
We can go further and give the user a text description per row.

**Comment by Joelgranados** [comment]
This has been added to my branch
