### ISSUE TITLE
Output CSV needs correct pot numbers - THIS IS A BIG DEAL AND NEEDS TO BE FIXED ASAP

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#160]
__CSV files from right-side chambers need to have their pot numbers start at 161 not 1. __

Pot numbers for a chamber (two cameras, R and L) go from 1 on the bottom left side of the left half of the chamber to 320 on the top right side of the right side of the chamber.

Output CSV files are per camera (i.e. two per chamber; one for the data from the Left camera and one for the data from the Right camera). Column values are the timestamp then the list of data from each pot numbers. From 1-160 for L chambers and 161-320 for R chambers. 
Currently the csv files in R-side cameras start at 1 and this breaks all downstream analysis.

**Comment by Joelgranados** [comment]
One way to fix this is to add to the configuration file a start offset for the output files. We can then add 161 to the chambers that need to start in that offset.

**Comment by Joelgranados** [comment]
Found an easy way to make this happen:
1) We do it in pot_detector pipeline component (pipecomponents.py:588)
2) Add a "starting offset" configuration variable to the component.
3) Make sure we start the pot ID count in this offset.

**Comment by kdmurray91** [comment]
bonus brownie points if you can hack it such that this parameter defaults to 161 if the camera name has an R at the end, e.g. GC05R

**Comment by Joelgranados** [comment]
This is fixed in cf7a042 in my branch.
