### ISSUE TITLE
Change output path of CSV files to "Results" folder in root

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#169]
I don't know if this is the best way to do it but dumping CSV folders into the folder of resized images is confusing. Unless you have a better suggestion/idea (please feel free to suggest!) I vote we dump all csv outputs into a "Results" folder.

Downsized and processed images go here:
  _..\a_data\TimeStreams\Borevitz\BVZ0036\Outputs_
CSV file outputs from the pipeline go here:
  _..\a_data\TimeStreams\Borevitz\BVZ0036\Results_

**Comment by Joelgranados** [comment]
This is out of scope. The pipeline should do as little as possible with respect to handling the end place of the outputs. A third application should take care of handling the output and putting it where you want it.

Note that I'm not saying that this should not be done, I'm just saying that it should not be done by timestreamlib library.

One proposal is a new project that uses timestreamlib to produce output and then can handle where to put it and how to modify it.
