### ISSUE TITLE
Put info on AUDIT codes and code version into JSON @ start of audit file

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#172]
Can we use something like JSON (preferred) or xml to encode the first few lines of the AUDIT file. The idea would be to have a brief json section at the start of the AUDIT file that would list what the code meanings are, the run date and the code version so it could be loaded by the DB and other processes that are tracking code status. But maybe sticking json into a CSV will break it when it gets loaded into R or other programs? If we can't use JSON, can we at least comma separate it like "ITEM-NAME,VALUE" to make it a bit easier to parse?
_Run-Date,2015_09_01_13_04_55_00_
_Code-Version,1.0354_
_Code-meanings, _
_1, Exception-Faulty-argument-in-component _
etc.
**Do we need to preserve column count for all rows for R and other programs?** Probably is preferable since matlab will definitely choke on it id we don't (won't it?)

**Comment by Joelgranados** [comment]
This is just additional information for 171. I'm closing this one as a dup.

Why JSON? These are CSV files and should just be comma separated lines.

Importing a CSV, XML and JSON file into a DB is all possible. There is no added value in that sense to change to json or XML.

Matlab and R can cope with additional headers. There is no problem for R nor Matlab to skip some header lines. There is no reason to change the CSV format.
