### ISSUE TITLE
Output folder paths need to be timestream standards compliant

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#32]
Don't know what you guys decided on in your last discussion but as far as I know output format for all timestream names should be of form
EXPID/EXPID-CH-CAM#~fullres-processestep
ex: BVZ0036/BVZ0036-GC02L-C01~fullres-seg (for segmented "-cor" for color corrected)
Under that should be an _Data folder where all out put CSV files go.

Filenames should follow same naming format as timestreams with a timestamp down to the minute and "00" for seconds" for when the file was generated:
e.g. BVZ0036-GC02L-C01~area_2014_07_22_09_15_25_00.csv
e.g. BVZ0036-GC02L-C01~gcc_2014_07_22_09_15_25_00.csv

**Comment by Joelgranados** [comment]
Both these things are already in place
