### ISSUE TITLE
timestream videoiser

### ISSUE THREAD

**Issue by kdmurray91** [borevitzlab/timestreamlib#61]
Need a function that takes the standard 5 parameters, start, end, interval, daystart, dayend, and converts a timestream into a video. My vote is to convert to webm. This should be possible w/ opencv, right?

Note that this feature will wait till after the feature freeze.

K

**Comment by TimeScience** [comment]
Gareth, what would it take to make a basic pipeline to something like ffmpeg that take start,end and timestep data an spits out a movie.  Maybe it should email the user with the url when the movie is done?

Can you work on this as a side project? 

Specs:
* User sets start and end date using the usual time player slider bar
* _Which images to play:_ at first we could just use all frames but later we'd want the ability to set start time of morning and night and number of frames to skip (i.e. if we have 2700 frames and the user wants a 30sec 30fps movie you'd only play every 3rd frame=900 frames)
* (Optional) movie is cropped to zoomed view on screen if image is zoomed

**Comment by gdunstone** [comment]
Why is this in here? it has nothing to do with timestreamlib really.
What Tim seems to want it's a button on the player that gives you a video.

**Comment by gdunstone** [comment]
https://github.com/borevitzlab/site-phenocam-org/issues/106
