### ISSUE TITLE
Correct timestamp format for CSV outputs

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#89]
Output CSV's should be formatted like this:
(1) A row/timestamp for all possible timepoints based on the capture frequency. Start at midnight on the first night of the experiment through to midnight on the last night of the experiment. One timepoint for every possible time in the experiment (so for an experiment with a photo every 15 minutes there'd be a timepoint for every 15 minute interval throughout the entire experiment)

(2) Data from all pots goes in the same csv file. The row headers will be:
 TimeStamp, Timestamp" (yes, two timestamps, see below for explanation), PotNumber
* Make one file for each phenotype output and adhere to TX naming standards like: 
BVZ0036-GC02L-C01~fullres-segg-area.csv, etc
* The first three columns will be different versions of the TimeStamp. 
   - The first TimeStamp will be the UNIX timestamp (**seconds** since 00:00, 1 Jan 1970, **LOCAL TIME**)
   - The second timestamp is human readable should be in the format "YYYY/MM/DD HH:MM:SS PM" ex: 2014/08/15 10:15:26:00 AM" and will use the actual time the image was captured (note there is no comma between date and time, just a space)
* Pot number will typically go from 1 to 160 in growth chambers, values may vary for other experiments. In most experiments some pots will always be missing (i.e. color checker location etc), but **ALL** possible pot numbers for a given experiment should be included

(3) If there isn't a datapoint for a given time or plant, you still put a timepoint and fill a value for each pot (whether there is data or not) using the following standards:
Each cell has 4 possible values: numeric, NaN, +Inf and -Inf.
* _Numeric_ value means that the vision algorithm was successful
* _NaN_ means that the vision algorithm was unsuccessful
* _+Inf_ mark the date/time that I ignored (i.e. images may have been recorded but they are outside of hours chosen for processing etc)
* _-Inf_ mark the dates that were supposed to be photographed and were not.

**Comment by Joelgranados** [comment]
The audit file takes care of this. It gives an error code for failures. We also add NaNs on the output csv files to indicate error.
